/**
 * The React renderer: mounts a scene into the page.
 *
 * This is the ONLY module in stillsmith that renders anything, and the only one
 * that imports `react-dom`. The Vite plugin loads it by path
 * (`dist/<framework>/runtime.js`, chosen from `config.framework`), so supporting
 * Vue or Svelte means adding a sibling that exports the same `start()` — no
 * change to capture, annotations, discovery, or the config.
 *
 * It runs inside the consumer's own Vite build, so it shares their React, their
 * aliases, and their CSS.
 */
import { StrictMode, type ReactNode } from "react";
import { flushSync } from "react-dom";
import { createRoot, type Root } from "react-dom/client";

import { type SceneModule, sceneId, sceneIdFromFile } from "../scene-utils.js";
import type { Scene, Setup } from "../types.js";

/**
 * Capture polls for this. Set once React has committed the scene — `load` and
 * `networkidle` both fire long before that, since the runtime imports the scene
 * module asynchronously.
 */
const READY_ATTR = "data-stillsmith-ready";

/**
 * Set instead of `READY_ATTR` when the scene never got as far as rendering.
 * Capture reads the message off it, so a scene that fails to import says why
 * rather than timing out with nothing to report.
 */
const ERROR_ATTR = "data-stillsmith-error";

/**
 * How long to wait for the two settle frames before giving up on them.
 *
 * Generous, because the happy path never reaches it — a page that paints runs
 * both callbacks inside ~32ms — and overrunning it costs capture only the wait.
 */
const PAINT_BACKSTOP_MS = 250;

/**
 * Give the browser two frames to lay the tree out and paint it — one for style
 * and layout, one for the paint — then run `done`.
 *
 * The frames settle the paint; they are not what readiness waits on. A frame is
 * not ours to promise: `requestAnimationFrame` only runs when the compositor
 * produces one, and a page can decline to — nothing to paint, a throttled
 * renderer, a machine under load. Readiness must not be able to hang on that, so
 * a timer releases it regardless and the frames only get to make it sooner.
 */
function settle(done: () => void): void {
  let fired = false;
  const once = () => {
    if (fired) return;
    fired = true;
    done();
  };

  requestAnimationFrame(() => requestAnimationFrame(once));
  setTimeout(once, PAINT_BACKSTOP_MS);
}

/**
 * Render a tree and signal readiness once it is committed.
 *
 * `root.render` only *schedules* a render, which quietly made the old two-frame
 * wait load-bearing: the frames stood in for React's commit as much as for the
 * paint, and "ready" meant "two frames have passed and React has presumably
 * caught up". `flushSync` commits before it returns, so the commit is the gate
 * and the frames are left doing nothing but settling the paint.
 *
 * Signalling from a `useEffect` in a wrapper component would read better and
 * does not work: this module is prebuilt and served straight off disk, outside
 * the consumer's module graph, so the `react` it imports is not necessarily the
 * instance react-dom hands the hook dispatcher to, and a hook here dies with
 * "Invalid hook call". `flushSync` is a react-dom API belonging to the same
 * instance that owns the root, so it is always coherent. Hence no hooks in this
 * file — scene components are compiled by the consumer's Vite and may use them
 * freely.
 */
function renderAndSignal(root: Root, node: ReactNode): void {
  flushSync(() => root.render(node));
  settle(() => document.documentElement.setAttribute(READY_ATTR, "true"));
}

function Passthrough({ children }: { children: ReactNode }) {
  return <>{children}</>;
}

function Message({ title, body }: { title: string; body: ReactNode }) {
  return (
    <div style={{ padding: 32, font: "13px/1.6 ui-monospace, monospace" }}>
      <strong>{title}</strong>
      <div style={{ marginTop: 12 }}>{body}</div>
    </div>
  );
}

/** The contract every framework runtime implements. */
export interface StartOptions {
  /** Absolute scene file path → dynamic importer. Generated by the Vite plugin. */
  scenes: Record<string, () => Promise<SceneModule>>;
  setup?: Setup<ReactNode>;
}

export async function start(options: StartOptions): Promise<void> {
  const root = createRoot(document.getElementById("root") as HTMLElement);

  // Every path out of `mount` — a scene, the index, an error — renders through
  // here, so every one of them ends up signalling readiness.
  const show = (node: ReactNode) => renderAndSignal(root, node);

  try {
    await mount(options, show);
  } catch (err) {
    /**
     * A scene module that throws at the top level, or imports something that
     * isn't there, rejects the dynamic import in `resolveScene` — and a rejected
     * promise is not a `pageerror`, so without this the page just sits there and
     * capture times out having seen nothing at all. Hang the message on the
     * document where capture can read it, and show it in `stillsmith dev` too.
     */
    const detail = err instanceof Error ? (err.stack ?? err.message) : String(err);
    document.documentElement.setAttribute(ERROR_ATTR, detail);
    console.error("[stillsmith] scene failed to load", err);

    show(
      <Message
        title="Scene failed to load."
        body={<pre style={{ margin: 0, whiteSpace: "pre-wrap" }}>{detail}</pre>}
      />,
    );
  }
}

/** Resolve the requested scene and render it. Throws if it can't be loaded. */
async function mount({ scenes, setup }: StartOptions, show: (node: ReactNode) => void) {
  const params = new URLSearchParams(window.location.search);
  const scheme = params.get("theme") === "dark" ? "dark" : "light";

  // Before any scene renders, so the first paint is already themed.
  setup?.applyColorScheme?.(scheme);

  const entry = await resolveScene(scenes, params);
  if (!entry) {
    const known = Object.keys(scenes).map(sceneIdFromFile).sort();
    show(
      <Message
        title="stillsmith"
        body={
          known.length ? (
            <ul>
              {known.map((id) => (
                <li key={id}>
                  <a href={`?scene=${encodeURIComponent(id)}&theme=${scheme}`}>{id}</a>
                </li>
              ))}
            </ul>
          ) : (
            <>No scenes matched the `scenes` globs in stillsmith.config.tsx.</>
          )
        }
      />,
    );
    return;
  }

  const scene = entry.mod.default as Scene<ReactNode> | undefined;
  if (!scene || typeof scene.render !== "function") {
    show(
      <Message
        title={`Scene "${entry.id}" has no usable default export.`}
        body="A scene file must `export default { id?, render }`."
      />,
    );
    return;
  }

  const Wrapper = setup?.wrapper ?? Passthrough;
  const SceneWrapper = scene.wrapper ?? Passthrough;

  show(
    <StrictMode>
      <Wrapper>
        <SceneWrapper>{scene.render()}</SceneWrapper>
      </Wrapper>
    </StrictMode>,
  );
}

/**
 * Capture navigates by `?file=` — discovery already resolved the exact module,
 * so there's nothing to search and nothing to get wrong. `?scene=<id>` is the
 * human/browsable form: it tries the filename convention first and only falls
 * back to loading every module when a scene has overridden its `id`.
 */
async function resolveScene(
  scenes: StartOptions["scenes"],
  params: URLSearchParams,
): Promise<{ id: string; mod: SceneModule } | null> {
  const file = params.get("file");
  if (file) {
    const load = scenes[file];
    if (!load) return null;
    const mod = await load();
    return { id: sceneId(file, mod), mod };
  }

  const wanted = params.get("scene");
  if (!wanted) return null;

  const byFilename = Object.entries(scenes).find(([f]) => sceneIdFromFile(f) === wanted);
  if (byFilename) {
    const mod = await byFilename[1]();
    if (sceneId(byFilename[0], mod) === wanted) return { id: wanted, mod };
  }

  for (const [f, load] of Object.entries(scenes)) {
    const mod = await load();
    if (sceneId(f, mod) === wanted) return { id: wanted, mod };
  }
  return null;
}
